
# # Informer
# python -u run.py --is_training 1 --root_path ./dataset/electricity/ --data_path electricity.csv --task_id ECL --model Informer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 321 --dec_in 321 --c_out 321 --des 'Exp' --itr 1 --gpu 0 --test_train_num 1000 --run_select_with_distance --selected_data_num 10 --adapted_lr_times 500 --remove_distance --remove_cycle > ECL_In_wo_dist_wo_cycle_wo_near.txt
# python -u run.py --is_training 1 --root_path ./dataset/electricity/ --data_path electricity.csv --task_id ECL --model Informer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 321 --dec_in 321 --c_out 321 --des 'Exp' --itr 1 --gpu 0 --test_train_num 1000 --run_select_with_distance --selected_data_num 10 --adapted_lr_times 500 --remove_distance --remove_cycle > ECL_In_wo_dist_wo_cycle.txt
# python -u run.py --is_training 1 --root_path ./dataset/electricity/ --data_path electricity.csv --task_id ECL --model Informer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 321 --dec_in 321 --c_out 321 --des 'Exp' --itr 1 --gpu 0 --test_train_num 1000 --run_select_with_distance --selected_data_num 10 --adapted_lr_times 500 --remove_distance > ECL_In_wo_dist.txt


# # ETSformer
# python -u run.py --root_path ./dataset/electricity/ --data_path electricity.csv --model ETSformer --data custom --features M --seq_len 336 --pred_len 96 --e_layers 2 --d_layers 2 --enc_in 321 --dec_in 321 --c_out 321 --des 'Exp' --K 3 --learning_rate 3e-4 --itr 1 --gpu 0 --d_model 512 --is_training 1 --task_id ECL --lradj exponential_with_warmup --dropout 0.2 --label_len 0 --activation 'sigmoid' --test_train_num 1000 --run_select_with_distance --selected_data_num 10 --adapted_lr_times 1000 --remove_distance --remove_cycle --remove_nearest > ECL_ETS_wo_dist_wo_cycle_wo_near.txt
# python -u run.py --root_path ./dataset/electricity/ --data_path electricity.csv --model ETSformer --data custom --features M --seq_len 336 --pred_len 96 --e_layers 2 --d_layers 2 --enc_in 321 --dec_in 321 --c_out 321 --des 'Exp' --K 3 --learning_rate 3e-4 --itr 1 --gpu 0 --d_model 512 --is_training 1 --task_id ECL --lradj exponential_with_warmup --dropout 0.2 --label_len 0 --activation 'sigmoid' --test_train_num 1000 --run_select_with_distance --selected_data_num 10 --adapted_lr_times 1000 --remove_distance --remove_cycle > ECL_ETS_wo_dist_wo_cycle.txt
# python -u run.py --root_path ./dataset/electricity/ --data_path electricity.csv --model ETSformer --data custom --features M --seq_len 336 --pred_len 96 --e_layers 2 --d_layers 2 --enc_in 321 --dec_in 321 --c_out 321 --des 'Exp' --K 3 --learning_rate 3e-4 --itr 1 --gpu 0 --d_model 512 --is_training 1 --task_id ECL --lradj exponential_with_warmup --dropout 0.2 --label_len 0 --activation 'sigmoid' --test_train_num 1000 --run_select_with_distance --selected_data_num 10 --adapted_lr_times 1000 --remove_distance > ECL_ETS_wo_dist.txt


# Crossformer
python -u run.py --root_path ./dataset/electricity/ --data_path electricity.csv --model Crossformer --data custom --features M --seq_len 336 --pred_len 96 --enc_in 321 --dec_in 321 --c_out 321 --des 'Exp' --learning_rate 5e-4 --itr 1 --gpu 0 --is_training 1 --seg_len 12 --d_model 64 --d_ff 128 --e_layers 3 --n_heads 2 --task_id ECL --dropout 0.2 --gpu 1 --test_train_num 1000 --run_select_with_distance --selected_data_num 10 --adapted_lr_times 20 --remove_distance --remove_cycle --remove_nearest > ECL_Cross_wo_dist_wo_cycle_wo_near.txt
python -u run.py --root_path ./dataset/electricity/ --data_path electricity.csv --model Crossformer --data custom --features M --seq_len 336 --pred_len 96 --enc_in 321 --dec_in 321 --c_out 321 --des 'Exp' --learning_rate 5e-4 --itr 1 --gpu 0 --is_training 1 --seg_len 12 --d_model 64 --d_ff 128 --e_layers 3 --n_heads 2 --task_id ECL --dropout 0.2 --gpu 1 --test_train_num 1000 --run_select_with_distance --selected_data_num 10 --adapted_lr_times 20 --remove_distance --remove_cycle > ECL_Cross_wo_dist_wo_cycle.txt
python -u run.py --root_path ./dataset/electricity/ --data_path electricity.csv --model Crossformer --data custom --features M --seq_len 336 --pred_len 96 --enc_in 321 --dec_in 321 --c_out 321 --des 'Exp' --learning_rate 5e-4 --itr 1 --gpu 0 --is_training 1 --seg_len 12 --d_model 64 --d_ff 128 --e_layers 3 --n_heads 2 --task_id ECL --dropout 0.2 --gpu 1 --test_train_num 1000 --run_select_with_distance --selected_data_num 10 --adapted_lr_times 20 --remove_distance > ECL_Cross_wo_dist.txt
